### ISSUE TITLE
[Feature]: Specify ABIs for libs

### ISSUE THREAD

**Issue by XayahSuSuSu** [LottieFiles/dotlottie-android#24]
It's not elegant to pack [them](https://github.com/LottieFiles/dotlottie-android/tree/main/dotlottie/src/main/jniLibs) all into one apk, can we publish different flavors for different ABIs?

e.g.
```
dependencies {
    implementation("com.github.LottieFiles:dotlottie-android-arm64:0.0.3")
    implementation("com.github.LottieFiles:dotlottie-android-x86_64:0.0.3")
}
```

**Comment by afsalz** [comment]
Hi @XayahSuSuSu,

Thanks for the suggestion. Implementing different flavors for different ABIs is a great idea. We will work on this for future versions to optimize our APK size.

**Comment by XayahSuSuSu** [comment]
Workaround: https://github.com/XayahSuSuSu/Android-DataBackup/pull/248

**Comment by afsalz** [comment]
Hi @XayahSuSuSu 

We had a discussion about your request to publish separate APK for each ABI. We appreciate your feedback and wanted to share our reasoning for the current approach.

Releasing separate ABI-specific artifacts would require different artifact IDs, which we believe is unnecessary for an AAR bundle. The universal AAR should suit the needs of the majority.

We’ve decided to stick with a universal AAR that includes all ABIs, similar to other libraries we came across. This ensures broad compatibility and simplifies integration.

For users concerned about APK size, we’ve added a section to our README on using abiFilters in your build.gradle to exclude unwanted ABIs. https://github.com/LottieFiles/dotlottie-android/pull/35/files

**Comment by XayahSuSuSu** [comment]
> Hi @XayahSuSuSu
> 
> We had a discussion about your request to publish separate APK for each ABI. We appreciate your feedback and wanted to share our reasoning for the current approach.
> 
> Releasing separate ABI-specific artifacts would require different artifact IDs, which we believe is unnecessary for an AAR bundle. The universal AAR should suit the needs of the majority.
> 
> We’ve decided to stick with a universal AAR that includes all ABIs, similar to other libraries we came across. This ensures broad compatibility and simplifies integration.
> 
> For users concerned about APK size, we’ve added a section to our README on using abiFilters in your build.gradle to exclude unwanted ABIs. https://github.com/LottieFiles/dotlottie-android/pull/35/files

There's no need to split ABIs with this guide indeed. Thanks for your great work!
