### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [LottieFiles/dotlottie-android#29]
I could find no license information in the repo. Could you please clarify what license this project falls under? Thanks in advance!

**Comment by afsalz** [comment]
Hi @IzzySoft , thanks for bringing this up. This project is under the MIT license, and we will be adding that in.

**Comment by IzzySoft** [comment]
Wonderful, thanks a lot! Updated the scanner signatures here accordingly so scans don't raise a "non-free" warning.
