### ISSUE TITLE
in JAVA, addEventListener error 

### ISSUE THREAD

**Issue by contigo** [LottieFiles/dotlottie-android#31]
![2024-08-02 16 41 18](https://github.com/user-attachments/assets/5ce156b2-32b4-4074-b91a-8e4621ce2af6)

If I create a lottieView in Java code and add an event, an error continues. 

The following error message is displayed in DotLottieEventListener: 

Class 'Anonymous class derived from DotLottieEventListener' must implement abstract method 'onLoop-WZ4Q5Ns(int)' in 'DotLottieEventListener'

**Comment by afsalz** [comment]
Hi @contigo we just released a fixed for this. Please try our latest version `com.github.LottieFiles:dotlottie-android:0.4.1`
