### ISSUE TITLE
[Feature] Support x86 devices

### ISSUE THREAD

**Issue by XayahSuSuSu** [LottieFiles/dotlottie-android#32]
There are no libs for x86 devices, can you add support for it?

https://github.com/LottieFiles/dotlottie-android/tree/main/dotlottie/src/main/jniLibs

**Comment by theashraf** [comment]
Hi @XayahSuSuSu, we're working on adding support for x86 architecture. Thanks!

**Comment by afsalz** [comment]
hi @XayahSuSuSu We have added support for the x86 architecture in the latest update 🚀 (v0.5.0). However, we haven’t been able to test it on x86 devices. We would greatly appreciate your help in testing this update on your end.

**Comment by XayahSuSuSu** [comment]
> hi @XayahSuSuSu We have added support for the x86 architecture in the latest update 🚀 (v0.5.0). However, we haven’t been able to test it on x86 devices. We would greatly appreciate your help in testing this update on your end.
> 
> If it doesn’t work as expected, feel free to reopen this issue. 🙏🏽

It works fine, thanks!
